server:
  port: 8080
spring:
  jpa:
    database: mysql
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/njuTJenv?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: zhanglingzhe0820
oos:
  accessKey: c4582dec5d0809103126
  secretKey: 47c783687d4c452c5d71b817b8c481915fb0094a
  endPoint: http://oos-bj2.ctyunapi.cn
  bucketName: njuTJEnvironment
aliyun:
  akId: LTAIfeJPa5mmsKhL
  akSecret: Dfz3Tj7Tyuojl84vSBHX7E9eluivj5
  imageHostUrl: https://dtplus-cn-shanghai.data.aliyuncs.com/image/tag
wechat:
  url: https://api.weixin.qq.com/sns/jscode2session?appid=
  id: wx85dcce057baa45b8
  secret: e3dfe65496ca25ece4429585350b309d
